import "./globals.css";
import "../public/css/plugins.css";
import ClientWrapper from "./components/ClientWrapper";
import Navbar from "./components/Navbar";
import Preloader from "./components/Preloader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ClientWrapper>
          <div className="cursor d-none d-lg-block"></div>
          <Preloader />
          <a href="#" id="scroll-top" className="back-to-top-btn">
            <i className="bi bi-arrow-up"></i>
          </a>
          <Navbar />
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
