import "./globals.css";
import "../public/css/plugins.css";
import ClientWrapper from "./components/ClientWrapper";
import Navbar from "./components/Navbar";
import Preloader from "./components/Preloader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <ClientWrapper>
          <Preloader />
          <Navbar />
          {children}
        </ClientWrapper>
      </body>
    </html>
  );
}
