import "./globals.css";
import "./styles/plugins.css";
import ClientWrapper from "./components/ClientWrapper";
import Navbar from "./components/Navbar";
import Preloader from "./components/Preloader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="scroll-hide">
        <ClientWrapper>
          {/* ✅ Ensure Preloader Runs First */}
          <Preloader />

          {/* ✅ Back to Top Button */}
          <a href="#" id="scroll-top" className="back-to-top-btn">
            <i className="bi bi-arrow-up"></i>
          </a>

          {/* ✅ Navbar */}
          <Navbar />

          {/* ✅ Page Content */}
          <main>{children}</main>
        </ClientWrapper>
      </body>
    </html>
  );
}
